apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.commander.appName }}
spec:
  ports:
    - port: {{ .Values.commander.webPort }}
      targetPort: {{ .Values.commander.localPort }}
      name: {{ .Values.commander.appName }}
      protocol: TCP
  selector:
    app: {{ .Values.commander.appName }}
  type: LoadBalancer