# Default values for api-chart.
namespace: aethersight

api:
  appName: aethersight-api
  replicaCount: 2
  revisionHistoryLimit: 2
  webPort: 8080
  image: ghcr.io/aetrius/aether-sight/aether-api:main
  loadBalancerIP: 192.168.2.5
  # imagePullSecret: regcred-aethersight

consumer:
  appName: aethersight-consumer
  replicaCount: 2
  revisionHistoryLimit: 2
  webPort: 6379
  image: ghcr.io/aetrius/aether-sight/aether-redis-consumer:main
