apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-my-release-redis-replicas-2
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
    volume.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
  volumeMode: Filesystem