---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.appName }}
spec:
  ports:
    - port: {{ .Values.api.webPort }}
      targetPort: {{ .Values.api.webPort }}
      name: {{ .Values.api.appName }}
      protocol: TCP
  selector:
    app: {{ .Values.api.appName }}
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: {{ .Values.api.loadBalancerIP }}